[package]
name = "rustlib_000"
version = "0.1.0"
authors = ["mapleAndwoman <fangshengzhou@hisilicon.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]
name = "selflib"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
